name: tv-series-notifier
on:
    schedule:
        - cron: '00 06 * * *' # ~9:00 MSK (+03)
    push:
        branches: main
jobs:
    notifier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'

            - name: Install dependencies
              run: npm install

            - name: Notify
              run: node index.js
              env:
                  TVTIME_COOKIE: ${{ secrets.TVTIME_COOKIE }}
                  WEBHOOK_PATHS: ${{ secrets.WEBHOOK_PATHS }} # ["123", "321"]
