name: tv-series-notifier
on:
    schedule:
        - cron: '00 05 * * *' # ~9:00 MSK (+04)
    push:
        branches: main
jobs:
    notifier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm install
            - name: Update
              uses: ./
              env:
                  TVTIME_COOKIE: ${{ secrets.TVTIME_COOKIE }}
                  WEBHOOK_PATH: ${{ secrets.WEBHOOK_PATH }}
